server:
  port: 8081
  error:
    include-exception: true
    include-stacktrace: always
  servlet:
    session:
      timeout: 1m

spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: metlife-hackertone-team01
  servlet:
    multipart:
      max-request-size: -1
      max-file-size: -1
#  datasource:
#    url: jdbc:mysql://localhost:3306/chatmetlife
#    username: root # ${DB_USERNAME}
#    password: 1234 # ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        format_sql: true #false로 변경
        show_sql: true #false로 변경
        use_sql_comments: true #false로 변경
        default_batch_fetch_size: 1000
    hibernate:
      ddl-auto: none
      generate-ddl: false
      naming: #mybatis camelcase 유지
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

# 로그레벨 -> 실제 production일 시 debug
logging:
  level:
    root: info # ${LOG_LEVEL}
    com:
      querydsl:
        sql: debug
  config: classpath:logback-spring.xml

#acturator 설정 (없어도 됨)
management:
  endpoint:
    health:
      show-details: always #never
#    redis:
#      enabled: false

# 기타 yml 파일 호출 건이 있을 시 하단에 기입
# resource:

# 클라우드 관련 설정 (aws용으로 세팅이라 보고... 안쓰면 지우기)
#cloud:
#  aws:
#    credentials:
#      accessKey: ${AWS_S3_ACCESS_KEY}
#      secretKey: ${AWS_S3_SECRET_KEY}
#    s3:
#      bucket: ${AWS_S3_BUCKET}
#    cdn:
#      url: ${AWS_CDN_URL}
#    region:
#      static: ${AWS_REGION_NAME}
#    stack:
#      auto: false
#    parameter-store:
#      roleArn: ${AWS_PARAMETER_STORE_ROLE_ARN}
#      accessKey: ${AWS_PARAMETER_STORE_ACCESS_KEY}
#      secretKey: ${AWS_PARAMETER_STORE_SECRET_KEY}
#      dekName: ${AWS_PARAMETER_STORE_DEK_NAME}
#      ivName: ${AWS_PARAMETER_STORE_IV_NAME}
#      region: ${AWS_PARAMETER_STORE_REGION}

open-ai:
  key: 05ff7fed90d04e27a5a0887f0d81b0f9
  endpoint: https://oai-metlife-team001.openai.azure.com/
  deployment-name: gpt4-metlife-team01
